//import './js/module-1-1.js'
//import './js/hw-01.js'
//import './js/hw-01-01.js'
//import './js/hw-02.js'
//import './js/hw-03.js'
//import './js/hw-04.js'
//import './js/module-5-1-constructor.js'
//import './js/mentor.js'
import './js/module-5-1.js'
import './js/module-5-1-classes.js'

